/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: kirigami318 (https://sketchfab.com/kirigami318)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/asus-rog-zephyrus-duo-gx551qm-2c7f8c0e2bbc406292fe53401c4f8aa2
Title: Asus ROG Zephyrus Duo GX551QM
*/

import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/computer.glb");
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.1, -0.7]} rotation={[-0.1, 0, 0]}>
        <mesh
          geometry={nodes.Object_14.geometry}
          material={materials.plastichead}
        />
        <mesh
          geometry={nodes.Object_15.geometry}
          material={materials.display_primary}
        />
        <mesh
          geometry={nodes.Object_16.geometry}
          material={materials.rog_logo}
        />
        <mesh
          geometry={nodes.Object_17.geometry}
          material={materials["Material.001"]}
        />
      </group>
      <group position={[0, 0.1, -0.7]} rotation={[-0.1, 0, 0]}>
        <mesh
          geometry={nodes.Object_48.geometry}
          material={materials.material_8}
        />
        <mesh geometry={nodes.Object_49.geometry} material={materials.key_f} />
      </group>
      <mesh
        geometry={nodes.Object_4.geometry}
        material={materials.body_metal}
      />
      <mesh
        geometry={nodes.Object_6.geometry}
        material={materials.body_metal}
      />
      <mesh
        geometry={nodes.Object_7.geometry}
        material={materials.some_blacc}
      />
      <mesh
        geometry={nodes.Object_9.geometry}
        material={materials.body_metal}
      />
      <mesh
        geometry={nodes.Object_10.geometry}
        material={materials.some_blacc}
      />
      <mesh
        geometry={nodes.Object_12.geometry}
        material={materials.total_black}
      />
      <mesh
        geometry={nodes.Object_19.geometry}
        material={materials.body_metal}
      />
      <mesh
        geometry={nodes.Object_20.geometry}
        material={materials.some_blacc}
      />
      <mesh
        geometry={nodes.Object_22.geometry}
        material={materials.total_black}
      />
      <mesh
        geometry={nodes.Object_24.geometry}
        material={materials.body_metal}
      />
      <mesh
        geometry={nodes.Object_26.geometry}
        material={materials.body_metal}
      />
      <mesh
        geometry={nodes.Object_28.geometry}
        material={materials.body_metal}
      />
      <mesh
        geometry={nodes.Object_30.geometry}
        material={materials.body_metal}
      />
      <mesh geometry={nodes.Object_32.geometry} material={materials.rog_logo} />
      <mesh geometry={nodes.Object_34.geometry} material={materials.material} />
      <mesh geometry={nodes.Object_36.geometry} material={materials.material} />
      <mesh geometry={nodes.Object_38.geometry} material={materials.material} />
      <mesh geometry={nodes.Object_40.geometry} material={materials.material} />
      <mesh geometry={nodes.Object_42.geometry} material={materials.material} />
      <mesh geometry={nodes.Object_44.geometry} material={materials.material} />
      <mesh geometry={nodes.Object_46.geometry} material={materials.material} />
      <mesh geometry={nodes.Object_51.geometry} material={materials.material} />
      <mesh
        geometry={nodes.Object_53.geometry}
        material={materials.display_blank}
      />
      <mesh geometry={nodes.Object_55.geometry} material={materials.numpad} />
      <mesh geometry={nodes.Object_57.geometry} material={materials.metal} />
      <mesh
        geometry={nodes.Object_58.geometry}
        material={materials.plastic_black}
      />
      <mesh geometry={nodes.Object_59.geometry} material={materials.yellow} />
      <mesh
        geometry={nodes.Object_60.geometry}
        material={materials.total_black}
      />
      <mesh geometry={nodes.Object_62.geometry} material={materials.metal} />
      <mesh
        geometry={nodes.Object_63.geometry}
        material={materials.total_black}
      />
      <mesh geometry={nodes.Object_64.geometry} material={materials.yellow} />
      <mesh
        geometry={nodes.Object_65.geometry}
        material={materials.plastic_black}
      />
      <mesh geometry={nodes.Object_67.geometry} material={materials.metal} />
      <mesh
        geometry={nodes.Object_68.geometry}
        material={materials.total_black}
      />
      <mesh
        geometry={nodes.Object_69.geometry}
        material={materials.plastic_black}
      />
      <mesh
        geometry={nodes.Object_71.geometry}
        material={materials.plastic_black}
      />
      <mesh
        geometry={nodes.Object_73.geometry}
        material={materials.body_metal}
      />
      <mesh geometry={nodes.Object_74.geometry} material={materials.panel} />
      <mesh geometry={nodes.Object_75.geometry} material={materials.Material} />
      <mesh
        geometry={nodes.Object_77.geometry}
        material={materials.body_metal}
      />
      <mesh
        geometry={nodes.Object_79.geometry}
        material={materials.plastichead}
      />
      
    </group>
  );
}

useGLTF.preload("/computer.glb");
